spring.application.name=api-local-link-manager

server.port=9000
server.shutdown=immediate

spring.datasource.url=jdbc:postgresql://localhost:5432/api_local_link_manager
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
